name: Build and Deploy
on:
  push:
    branches:
      - master  # 只在master上push触发部署
    paths-ignore: # 下列文件的变更不触发部署，可以自行添加

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # 使用ubuntu系统镜像运行自动化脚本
    steps:  # 自动化步骤
      - name: Checkout  ️
        uses: actions/checkout@v2.3.4 # 第一步，下载代码仓库

      - name: Install and Build
        run: |
          yarn install
          yarn run build
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          BRANCH: blog
          FOLDER: dist
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}